"""empty message

Revision ID: 093c06768059
Revises: 
Create Date: 2020-07-27 02:15:23.802703

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from app.payment.models import CURRENCY_CHOICE

# revision identifiers, used by Alembic.
revision = '093c06768059'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(precision='8', decimal_return_scale='2'), nullable=True),
    sa.Column('currency', sqlalchemy_utils.types.choice.ChoiceType(choices=CURRENCY_CHOICE), nullable=True),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    # ### end Alembic commands ###
